name: Laravel

on:
  push:
    branches: master
  pull_request:
    branches: master

jobs:
  laravel-tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install Dependencies
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
    - name: Run Composer
        run: composer install -n --prefer-dist
    - name: Install Node
        run: |
          curl -sL https://deb.nodesource.com/setup_10.x | sudo -E bash -
          sudo apt-get install -y nodejs
    - name: Run NPM
        run: npm install
    - name: Generate key
        run: php artisan key:generate
    - name: Directory Permissions
        run: chmod -R 777 storage bootstrap/cache
    